### ISSUE TITLE
Frage zu pull requests

### ISSUE THREAD

**Issue by Scenay** [Aequivinius/uibk-python#164]
Hallo,
ich wollte fragen obs irgendwie die Möglichkeit gibt, nicht gleich ein ganzes commit (oder sogar 2) als pull request zu machen, sondern das auf eine Datei zu beschränken. Beispielsweise habe ich bei der exercise 2 jetzt 4 Datein dabei, also auch Erklärung usw., weil ich da halt auch was reingeschrieben hatte, aber die waren ja nicht relevant. Eigentlich hätte ich nur die fizzbuzz.py abgeben (d.h. als pull request machen) wollen... . Hoffe, ich hab da nicht einfahch irgendwo was übersehen. (Habe im Internet dazu geschaut, bin aber eher noch mehr verwirrt davon.) Danke!

**Comment by Aequivinius** [comment]
Grundsätzlich sind zusätzliche Dateien kein Problem, die Tests laufen nur auf die `fizzbuzz.py`. Sie können auch einen weiteren `commit` mit der Löschung der überflüßigen Dateien hinzufügen, und dann so Ihr Projekt 'sauber' als `pull request` abgeben. 

Im Web Interface sind Ihre Handlungsmöglichkeiten etwas eingeschränkt, wenn Sie so nicht weiter kommen, dann können Sie auch den [Desktop Client](https://desktop.github.com/) ausprobieren.
