### ISSUE TITLE
Pull request ex4

### ISSUE THREAD

**Issue by Vizcachera** [Aequivinius/uibk-python#261]
Hi!
Beim Pull request ist der exercise-1 immer in Konflikt. Ich habs umbennet, gelöscht und trotzdem gehts nicht. 
Ideen? Danke!

**Comment by h0az** [comment]
Hast du schon versucht, den Konflikt lokal auf deinem Rechner zu lösen? Ich hatte beim Merge Pull Request dasselbe Problem mit `exercise-1-correctme.md` und habe Stunden erfolglos mit löschen, umbenennen etc. verbracht. In der Desktop-Version von GitHub (und einem passenden Text Editor) hat dann alles problemlos in 5 Minuten funktioniert.

**Comment by Vizcachera** [comment]
Hi @h0az !
Danke, es hat siche erledigt. Ich habe wieder alle "Fehler" im correctme.md eingebaut, dass es wie im Master branch ist und dann ist gegangen.
Aber, ich muss sagen, es war nervig mehr zeit damit zu verbringen, wie bei der Lösung der HÜ... :-)

**Comment by Aequivinius** [comment]
Das tut mir sehr Leid, ich werde mir für den nächsten Durchgang der Übung hierfür eine bessere Lösung überlegen!
