### ISSUE TITLE
Unable to arrive at a solution

### ISSUE THREAD

**Issue by TeraBT** [Aequivinius/uibk-python#285]
While testing the porter stemmer I always get the following error message:
"TypeError: 'NoneType' object is not subscriptable" concerning the following line:
if contains_vowel(word[:-1]) and word[:-1] == "y":

As far as I know, this seems to happen because the porter stemmer doesn't recognize the variable word as a list object. I don't really know how to rectify this and therefore I'm unable to test whether the steps are working properly. The funny thing is that many students implemented exactly the same if statement as I did, but it seems to be working for them. Maybe I'm overlooking something...

**Comment by Aequivinius** [comment]
We can take a moment after today's exercise to look at it - you're possibly *calling* the `contains_vowel` function with an empty object.

**Comment by Aequivinius** [comment]
By the way, with the new exericse-5 published, the repository should no longer test your submission for exercise-4, so make sure you run `pytest` on your machine before submitting your next pull request.
