### ISSUE TITLE
Same old, same old

### ISSUE THREAD

**Issue by Aaron-Mair** [Aequivinius/uibk-python#297]
Hi, I was trying to run pytest for exercise 5, but it brought up several errors that are not even related to the current exercise (it brought up errors in exercise 6 as well but I deleted that one already because I'm going to pull it again next week anyways):

![image](https://user-images.githubusercontent.com/80037336/115256132-3e8e9a80-a12f-11eb-9f20-69445ab9483c.png)

Also I tried running the program to see if it worked (more precisely: to see if I could run it, not if it actually works as it is intended to - that I can't check as I have not really an idea of what we are trying to do here), and it didn't run, it only inserted new lines: 

![image](https://user-images.githubusercontent.com/80037336/115257146-1a7f8900-a130-11eb-9564-2b40bfd22307.png)

To be honest I don't even know what to ask in this issue, I don't understand what I don't understand, sooo... yeah. Please help

**Comment by n-vdh** [comment]
Hi, bei pytest ist denke ich das Problem, dass du dich nicht im richtigen directory befindest. Wenn du zuerst `cd exercise-5` eingibst, wird auch nur exercise-5 getestet. Beim anderen Punkt würde ich mal testen, ob dein Programm überhaupt einen output hat, indem du unten irgendein Printstatement einfügst und schaust, ob das dann aufscheint.

**Comment by Aequivinius** [comment]
Yes, you can also check the last section of the `exercise-5-readme.md`, where I explain this a bit more. To check your current directory, you can type `pwd` in the console, it should show you where you are. If it's in `/home/runner/uibk-python`, typing `pytest` will run all tests for all projects; if you `cd exercise-5` first, `pwd` should output `/home/runner/uibk-python/exercise-5` and `pytest` should only look for tests for the exercise you are working on.

<img width="385" alt="Capture d’écran 2021-04-20 à 12 16 24" src="https://user-images.githubusercontent.com/11438440/115379964-58cd8480-a1d2-11eb-820a-e1cab7cdbf38.png">

Also, while I understand your frustration, use descriptive issue titles in future.
