### ISSUE TITLE
Assertion Errors in Ex5

### ISSUE THREAD

**Issue by TeraBT** [Aequivinius/uibk-python#301]
When running the code of exercise 5, I get the following Errors:

Windows:
![screenshot 480](https://user-images.githubusercontent.com/80151163/115405931-fa62cf00-a1ee-11eb-90c0-be705879fafd.jpg)
I thought that os.path.join() would automatically detect the OS

Ubuntu:
![screenshot 479](https://user-images.githubusercontent.com/80151163/115405551-a35cfa00-a1ee-11eb-9ddf-b62efd33c921.jpg)
Here, the first error doesn't occur, because the file paths match, but I don't understand this error either.

That's the output of the program. It looks like it does what it should:
![screenshot 481](https://user-images.githubusercontent.com/80151163/115406303-54639480-a1ef-11eb-9097-9f07040e1c4b.jpg)

**Comment by TeraBT** [comment]
As I've stated in my pull request, it doesn't make sense at all that everything's working now

**Comment by Aequivinius** [comment]
It's a bit difficult for me to see into your setup, especially since you're running it on your own machine, not on replit. We can take some time tomorrow after the exercise lesson to go through your code and setup.
