### ISSUE TITLE
A Question about Efficiency

### ISSUE THREAD

**Issue by TeraBT** [Aequivinius/uibk-python#305]
![image](https://user-images.githubusercontent.com/80151163/115447722-1d09dd80-a219-11eb-90d5-0e4de4cebf19.png)

Is it possible to rewrite this functions so it does f.write in a for-loop with every line without instantly deleting the line before writing the new one to the file and without using "a" but "w", as we always did to this point?

I ask this because I don't consider my approach (storing it all in the temporary variable all_data) to be the most efficient regarding the computing power that is used in the process. It would be a lot faster to just print line after line to a file and you wouldn't need as much RAM to do so. I don't know the maximum size for the string type, but there has to be a limit unless python is able to use all your available RAM, then it would depent on your specs, but it would be inefficient nonetheless.

---

Second question: Is there a more formal way to write `return 1` such as `return EXIT_SUCCESS`, for instance?

**Comment by Aequivinius** [comment]
Awesome that you're thinking about efficiency! 

In general, clarity of code is more important than efficiency. Code is usually more often read than it is run, and computational power these days is cheap compared to human brain time. So when in doubt, go for the option that is easiest to understand, even if it is not the most efficient.

Secondly, everything to do with the file system is slow. You'll usually want to do as much processing in RAM, and minimize interacting with files; so your approach is actually the better one. Again, RAM is also cheap.

Thirdly, so you can better understand how to interact with files, you could do the following:

```python
with open(path, 'w') as f:
   for item in list:
      do_something()
      f.write(item)```

Remember that `f.write()` appends to the file as long as the file is not closed. When the file is closed and opened again, it will overwrite the file:

```f = open(path)
f.write("First")
f.write("Second") # Will be appended
f.close()

f = open(path)
f.write("Third") # Will overwrite "First" and "Second"```

The same applies when you use the `with open(path) as f` notation.

**Comment by Aequivinius** [comment]
As for your second question: Not every function in python needs to have a `return` statement. The correct / pythonic way to deal with functions that don't return anything is to raise exceptions when something goes wrong - we're not looking at exceptions in this course, but if you're interested (and you should be, since it's a very elegant way to write code) you could read [this](https://realpython.com/python-exceptions/).

A simpler way, and easier to read, too, would be to `return True`, so you can call your `write_frequencies()` like this:

```is_okay = write_frequencies()
if is_okay:
   print("All went fine")
else:
   print("Problem writing files")
