### ISSUE TITLE
exercise-06: problem \n character

### ISSUE THREAD

**Issue by MagLoe1** [Aequivinius/uibk-python#321]
Hello,
when I tried to submit this week's exercise, I got the following [error message](https://github.com/Aequivinius/uibk-python/pull/320/checks):
```bash
   def test_write():
      tokenizer.write("Die Stadt verschwimmt wie hinter Glas.", 'test.csv')
      with open('test.csv','r') as f:
        test_file = f.readlines()
        test_line = test_file[1].split('\t')
        assert(test_line[0] == 'Stadt')
>       assert(test_line[1] == 'stadt')
E       AssertionError: assert 'stadt\n' == 'stadt'
E         - stadt
E         + stadt
E         ?      +
```

At first I thought it was referring to extra new lines in my output file (which I then avoidid by adding newline="" in the write() function (--> with open(output_path, "w", **newline=""**) as f:) ), but it turned out this was not the problem.

I think the problem is that the second word in each line contains a \n character, but the test does not allow e.g. "stadt\n" but only "stadt". But since the format of my output files looks identical to the test.csv file, I thought my code was correct and I don't know how to solve this problem.

Thank you and have a nice weekend,
Magdalena

**Comment by Aequivinius** [comment]
Can you please create a pull request with your code, so I can look at it? 

In the meantime, I've changed the test file in case it's an error in the test logic, either change line 24 of `tokenizer_test.py` to `assert(test_line[1].strip() == 'stadt')`, or pull in the changes into your repository.

**Comment by MagLoe1** [comment]
Hello,
thank you for your response! I just merged the updated tokenizer_test.py and now it worked, so it really was just the missing .strip() in line 24 of the test file :).
Thank you and have a nice weekend,
Magdalena

**Comment by Scenay** [comment]
Super, dass du das wieder gefunden hast, Magdalena! Das hat mich direkt motiviert, die Aufgabe auch gleich fertig zu machen - und ich denke, ich wäre verzweifelt bei dieser Fehlermeldung. Danke auch für die schnelle Lösung, @Aequivinius
