### ISSUE TITLE
exercise 6: workflow awaiting approval

### ISSUE THREAD

**Issue by lenigr01** [Aequivinius/uibk-python#329]
Hello!

I wanted to finish my exercise 6. I did a pull request but then I got the message "1 workflow awaiting approval". In fact, the check is not running. I did some research and then I read the following: When a first-time contributor submits a pull request to a public repository, a maintainer with write access must approve any workflow runs. Maybe I am a first-time contributor, because I had to delete my repository in order to get the latest version.

I would be very glad if you could help me! Thank you in advance!

Best wishes,

Lena

**Comment by Aequivinius** [comment]
This is possibly due to an update of github; I just approved all of the pending request.

**Comment by AlenaPardatscher** [comment]
Hello, the same error occured to me, the pytest went through, but now it doesn't even start checking.  Maybe it is the same problem as Lena had, I would be very grateful if you could help me there.
Thanks in advance, Alena

**Comment by Aaron-Mair** [comment]
I'm having the same issue
