### ISSUE TITLE
Ex6: unmergable

### ISSUE THREAD

**Issue by TeraBT** [Aequivinius/uibk-python#334]
Well, I've tried to delete the directory of ex6 and restore it etc., but it won't work. How can I solve the merge conflict?

**Comment by Aequivinius** [comment]
It was a bit difficult to find out, but it seems like the repeated deletion and readding of files made the automatic merge impossible. I fixed it for you, and it should all be fine now.

**Comment by TeraBT** [comment]
Thanks a lot! Yeah, first I've tried to discard all changes the way github suggested to me, but then it didn't accept it either.
