### ISSUE TITLE
fehler im Script

### ISSUE THREAD

**Issue by Vizcachera** [Aequivinius/uibk-python#337]
Hallo!

Ich glaube ich habe ein Denkfehler, oder Verständnisfehler

Mein Scripr schein mit files als input nicht zu funktioniern, es wirft keine Fehlermeldung, aber es wirft auch kein output.

Hier ein abschitt vom Code:

if sys.argv[1] == "-f":
    with open(sys.argv[2]) as f:
      input_string = f.read()

Ich weiß nicht wo der Fehler liegt, hat jemand einen Tipp?
Danke!

**Comment by TeraBT** [comment]
```
elif sys.argv[1] == "-f":
    with open(sys.argv[2], "r") as f:
      input_string = f.read()
```
Das wäre mein Code. Es liegt vielleicht daran, dass du das "r" für read vergessen hast. Versuch's mal damit :)
Lg

**Comment by Vizcachera** [comment]
@TeraBT Danke, ja, das kann gewesen sein :P oder der "elif"...
Auf jedem Fall jetzt ist gegangen. Vielen Dank!
