### ISSUE TITLE
Can't import anything

### ISSUE THREAD

**Issue by Brabl** [Aequivinius/uibk-python#445]
I can't work on binder, because it doesn't let me import anything, just keeps telling me there are no modules found named nltk etc . I tried installing nltk on my machine, but when I work with Pycharm, it keeps telling me it couldn't find nltk there either, even though the console tells me that I've already installed it.

**Comment by TeraBT** [comment]
Did you install nltk in poetry itself or globally? When running jupyter from poetry you need to have nltk installed in poetry itself.

I hope that helps!
