### ISSUE TITLE
Unable to pull origin on desktop

### ISSUE THREAD

**Issue by TeraBT** [Aequivinius/uibk-python#448]
![image](https://user-images.githubusercontent.com/80151163/122931507-3fc98700-d36d-11eb-86fd-18446a050b32.png)

First time I've encountered this error.

Is there a way to download these files directly? I can't find a download button and creating the subfolders of `corpus` myself would be very time consuming.

**Comment by Aequivinius** [comment]
You can either download the entire repository from github by clicking on the green `⬇️ Code` button and selecting `download as .zip`, or you can download the entire dataset from [here](https://www.cs.cmu.edu/~./enron/).
